### ISSUE TITLE
What is the best way to keep my instance up to date with the changes?

### ISSUE THREAD

**Issue by PierrickLozach** [haydenbleasel/next-forge#279]
Thanks for this great project. I love it!

However, once I have created my own instance, what is the best way to get all the latest changes? Should I download the new release and overwrite the files? 

What if I add my own code?

**Comment by haydenbleasel** [comment]
Hey @PierrickLozach great question. Right now there isn’t a way other than to manually diff the files, but I was thinking about a CLI command that downloads the diff between two versions.

**Comment by mnickkk** [comment]
One thing you could do is add `haydenbleasel/next-forge` as supplementary remote pull, see the diff and pick things that are added value to your project. This will obviously get more complex over time due to increasing deltas between the codebases, but starter kit is not something you should be syncing with. Maybe the maintainers of this repo could create and update a list of things worth porting (e.g. we fixed major auth security issue, here's a diff on how you can update your code to have this fix in your codebase).

**Comment by PierrickLozach** [comment]
HEy @haydenbleasel , I see your New update command update. Does this mean that there is a way to get the latest changes? Or does it still require manual diffs?

**Comment by haydenbleasel** [comment]
Hey @PierrickLozach yep we have a method now, check out [the Updates documentation](https://docs.next-forge.com/updates#upgrading-next-forge) on how to use it! One you pull the latest changes, you can modify them in case you want to manually merge your own changes.
