### ISSUE TITLE
Axiom as log drain

### ISSUE THREAD

**Issue by jerriclynsjohn** [haydenbleasel/next-forge#8]
Betterstack is great, but Axiom is a good contender, also cheap.

**Comment by haydenbleasel** [comment]
Great callout. I originally opted for BetterStack logs as we're using the status component, but Axiom appears to win out on pricing.

**Free Plan**
BetterStack: 1GB / mo with 3-day retention
Axiom: 500GB / mo with 30-day retention

**$25/mo Plan**
BetterStack: 30GB / mo with 15-day retention
Axiom: 1TB / mo with 95-day retention

If you're open to submitting a Pull Request I'm happy to review! Otherwise I'll explore it when I have some free time.
